import { Debug, Physics } from '@react-three/cannon';
import { Canvas } from '@react-three/fiber';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import Bird from '../components/Bird';
import CameraController from '../components/CameraController';
import Floor from '../components/Floor';
import Pillar from '../components/Pillar';
import useGameState from '../state/gameState';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { pillars, addPillar, gameStarted, startGame } = useGameState(
    ({ pillars, addPillar, gameStarted, startGame }) => {
      return { pillars, addPillar, gameStarted, startGame };
    }
  );

  useEffect(() => {
    document.addEventListener('keypress', (event) => {
      // Spacebar was clicked
      const key = event.key;
      if (key === 'p') {
        startGame();
      }
    });
  }, []);

  useEffect(() => {
    if (gameStarted) {
      addPillar();
      const interval = setInterval(() => {
        addPillar();
      }, 6000);

      return () => {
        console.log('--Clearing interval--');
        clearInterval(interval);
      };
    }
  }, [gameStarted]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Canvas
          camera={{
            fov: 75,
            near: 0.1,
            far: 1000,
            position: [0, 0, 10],
          }}
        >
          <CameraController />
          <ambientLight intensity={0.5} castShadow />
          <spotLight
            position={[10, 10, 10]}
            angle={0.15}
            penumbra={1}
            castShadow
          />
          <pointLight position={[-10, -10, -10]} castShadow />
          <Physics gravity={[0, -20, 0]} allowSleep={false}>
            <Debug color="black" scale={1}>
              <Bird />
              {pillars.map((pillar) => {
                return <Pillar key={pillar.id} pillar={pillar} />;
              })}
              <Floor />
            </Debug>
          </Physics>
        </Canvas>
      </main>
    </div>
  );
};

export default Home;
